name: Continuous Integration

on:
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Docker layers
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Build Docker containers
        run: docker-compose up -d --build

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install Composer dependencies
        run: docker-compose run php composer install --prefer-dist --no-progress --no-suggest

      - name: Run code style checker
        run: docker-compose run php composer ecs
      - name: Run tests
        run: docker-compose run php composer tests
