name: Continuous Integration

on:
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out GitHub repository
        uses: actions/checkout@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install Composer dependencies
        run: docker-compose run php composer install --prefer-dist --no-progress --no-suggest

      - name: Run code style checks
        run: docker-compose run php composer code-style

      - name: Run tests
        run: docker-compose run php composer tests
