name: Continuous Integration

on:
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker containers
        run: docker-compose up -d --build
      - name: Install Composer dependencies
        run: docker-compose run php composer install --prefer-dist --no-progress --no-suggest
      - name: Run code style checker
        run: docker-compose run php composer ecs
      - name: Run tests
        run: docker-compose run php composer tests
