name: Release

on:
  push:
    branches: [ master ]

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Draft Release
        uses: zendesk/action-create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: true
          tag_schema: semantic