name: Create Draft Release

on:
  push:
    branches:
      - master
    paths:
      - src/**

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out GitHub repository
        uses: actions/checkout@v2

      - name: Create draft release
        uses: zendesk/action-create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          prerelease: true
          tag_schema: semantic